apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-users
  namespace: todo-users
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: todo-users-role
  namespace: todo-users
rules:
  - apiGroups:
      - ""
    resources:
      ["*"]
    verbs:
      ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: todo-users-role-binding
  namespace: todo-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: todo-users-role
subjects:
  - kind: ServiceAccount
    name: todo-users
    namespace: todo-users